sonar.projectKey=nextjs-app
sonar.projectName=nextjs-app
sonar.sources=.
sonar.exclusions=node_modules/**,.next/**,out/**,coverage/**

# If you have tests / coverage later:
# sonar.tests=.
# sonar.test.inclusions=**/*.test.js,**/*.spec.js
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
