---
- name: Kubernetes prerequisites on all nodes
  hosts: k8s
  become: true
  roles:
    - k8s_common

- name: Initialize control-plane
  hosts: k8s_master
  become: true
  roles:
    - k8s_master

- name: Join workers
  hosts: k8s_workers
  become: true
  roles:
    - k8s_workers
