---
- name: Install Nexus
  hosts: nexus
  become: true
  roles:
    - nexus

- name: Install SonarQube
  hosts: sonarqube
  become: true
  roles:
    - sonarqube

- name: Install Prometheus + Grafana
  hosts: monitoring
  become: true
  roles:
    - monitoring
