---
- name: Disable swap (required)
  command: swapoff -a
  changed_when: false

- name: Remove swap entry from fstab
  replace:
    path: /etc/fstab
    regexp: '^\s*([^#].*)\s+swap\s+.*$'
    replace: '# \1 swap disabled by ansible'

- name: Load kernel modules for Kubernetes
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Apply sysctl params for Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Load modules now
  shell: |
    modprobe overlay
    modprobe br_netfilter
  changed_when: false

- name: Apply sysctl now
  command: sysctl --system
  changed_when: false

# containerd
- name: Install containerd
  apt:
    name: containerd
    state: present

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd config (first time only)
  shell: |
    containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Enable SystemdCgroup in containerd
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart and enable containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes

# kubeadm/kubelet/kubectl
- name: Add Kubernetes apt keyring
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key \
      | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repo
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /

- name: Install kubelet kubeadm kubectl
  apt:
    update_cache: yes
    name:
      - "kubelet={{ k8s_version_apt }}"
      - "kubeadm={{ k8s_version_apt }}"
      - "kubectl={{ k8s_version_apt }}"
    state: present

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
