replicaCount: 2

image:
  repository: docker.io/janith9988/nextjs-app
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

containerPort: 3000

ingress:
  enabled: true
  className: nginx
  host: nextjs.local
  path: /

resources: {}
